### List All Todos
http://localhost:8080/api/todos

###

POST http://localhost:8080/api/todos
Content-Type: application/json

{
"id": 1,
"title": "Task 1"
}


### Get Todo By ID
http://localhost:8080/api/todos/3


### Delete Todo By ID
DELETE http://localhost:8080/api/todos/2
